default:
  tags:
    - new-runner

stages:
  - tests
  - update

test:
  interruptible: true
  image: python:3.11
  stage: tests
  variables:
    TGS_SERVER_URL: '192.168.0.2:50051'

    SEQ_URL: 'http://test-seq/'
    SEQ_API_KEY: 'some-key'

    RABBITMQ_HOSTNAME: 'test-rabbit'
    RABBITMQ_PORT: '5672'
    RABBITMQ_USERNAME: 'test-rabbit-admin'
    RABBITMQ_PASSWORD: 'test-rabbit-password'
    RABBITMQ_VHOST: 'test-vhost'

  services:
    - name: datalust/seq:2024.3
      alias: test-seq
      variables:
        ACCEPT_EULA: 'Y'
        # password: <test-seq-password>
        SEQ_FIRSTRUN_ADMINPASSWORDHASH: 'QKHvzdRbM2pNTv0S1XKkl+l5RHJyhsnqhhwwTX0xVQPwDrSSB6AYDoZtumL8ut90i3v6sqQE2gBkDWE3iAvkD2R3DHaiMmZY9vNKDmJTZbdE'

    - name: rabbitmq:3.13.3-management
      alias: test-rabbit
      variables:
        RABBITMQ_DEFAULT_USER: 'test-rabbit-admin'
        RABBITMQ_DEFAULT_PASS: 'test-rabbit-password'
        RABBITMQ_DEFAULT_VHOST: 'test-vhost'

  script:
    - printenv
    - python -m pip install -r requirements-dev.txt
    - python -m unittest --failfast
  except:
    - _package

linter:
  interruptible: true
  stage: tests
  image: pipelinecomponents/pylint:latest
  script:
    - pylint src
    - pylint tests
  except:
    - _package

update-package:
  stage: update
  image: python:3.12-slim
  script:
    - source ./ci-jobs/update-package.sh
  only:
    - main
    - master

update-package-branch:
  stage: update
  variables:
    DEPLOYMENT_BRANCH: _package
  script:
    - git config user.name "Max Dubrovin"
    - git config user.email "max@cebb.pro"
    - git fetch origin $DEPLOYMENT_BRANCH
    - git checkout $DEPLOYMENT_BRANCH
    - git merge $CI_COMMIT_SHA --ff-only
    - git push https://deploy:$DEPLOYMENT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:$DEPLOYMENT_BRANCH
  only:
    - main
    - master
