# for tests

services:
  rabbit:
    hostname: test-rabbit
    image: rabbitmq:3.13.3-management
    restart: always
    ports:
      - 15672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'test-rabbit-admin'
      RABBITMQ_DEFAULT_PASS: 'test-rabbit-password'
      RABBITMQ_DEFAULT_VHOST: 'test-vhost'

  seq:
    hostname: test-seq
    image: datalust/seq:2024.3
    restart: always
    ports:
      - 15080:80
    environment:
      ACCEPT_EULA: 'Y'
      # password: <test-seq-password>
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: 'QKHvzdRbM2pNTv0S1XKkl+l5RHJyhsnqhhwwTX0xVQPwDrSSB6AYDoZtumL8ut90i3v6sqQE2gBkDWE3iAvkD2R3DHaiMmZY9vNKDmJTZbdE'
      RABBITMQ_DEFAULT_VHOST: 'test-vhost'
    volumes:
      - test_seq:/data

volumes:
  test_seq:
