# for tests

services:
  rabbit:
    hostname: test-rabbit
    image: rabbitmq:3.13.3-management
    restart: always
    ports:
      - 11001:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'test-rabbit-admin'
      RABBITMQ_DEFAULT_PASS: 'test-rabbit-password'
      RABBITMQ_DEFAULT_VHOST: 'test-vhost'

  seq:
    # after first start do not forget to create an API key
    hostname: test-seq
    image: datalust/seq:2024.3
    restart: always
    ports:
      - 11002:80
    environment:
      ACCEPT_EULA: 'Y'
      # command for generating password`s hash:
      # echo 'nimda' | docker run --rm -i datalust/seq config hash
      # this password: nimda
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: 'QCrQSzUel6Cn6VJ9iWPcSjG6GBfNUOvdlAqVgN27TFy/v+uOSQCjRuM5zmjVFu4G9YUkrtd45tVwv8/HWmofyJMG74c8xXXgolwB75b1jc5q'
    volumes:
      - seq:/data

volumes:
  seq:
