services:
  calculator-1:
    restart: always
    environment:
      INSTANCE_TAG: '01'
    build:
      context: ./default_microservice
    networks:
      cluster:
    depends_on:
      - rabbit

  calculator-2:
    restart: always
    environment:
      INSTANCE_TAG: '02'
    build:
      context: ./default_microservice
    networks:
      cluster:
    depends_on:
      - rabbit

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.13.3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: cluster-vhost
    networks:
      cluster:

networks:
  cluster:
    name: my-cluster
